language: python
python: 2.7
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls
script: coverage run --source=cloudshell_rest_api setup.py test
after_success: coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist
  user: Quali
  password:
    secure: YCbpiry0qY1FVB7yzVvg1L30/RWfhVmVrV9JCNOxXbHhBCy6jTb5/sTk/w4FUfx4qCqfYrE0YNQvVrESX9AI00qsSpJ8lOeLRcLduqJAwqR+y9LS+liWvav/4ACKB0mAv7ALqyjBe1RKXn723cYENR1oDYSO2wuhyyN/uUx5vhserRjJge8wC7P4HhE2BS4ZJYHccqK64e5mmOLfu1fq8EkbA3ZIQhL2sQyyXSwQLLSRafKDIKzdARBrMfzKBwn6W3RQ7ePteIBfBgVaE7CpytvmXJ9lJNXcgEw0rXfFX2KVAy0Cu6ozDuH2QakcvjbCjMdVJF+HlISIK0TABQQCazT3oMQvnBrkKubCl0hQDcVUxhA4/l8vGeGZ5BVqb+Yilhq8CKAtGqxDIpXoqjl+Gpv6Ehrc8/Bs6LhJhB+pQsjpO3iGiVtDRKPeIU8p74k+LLionoEKsKWtkupkV9ihsgARjmzynoD0w36H7wdKLfMNz8hjvzjCK8SqW0ZTgiKp16K8YWDNPHaejIKa+gtEpMzWQk093FhFOEZzYvweCHw0BrlrwZKm5tuBBLTe2XmIhCNkJOp0LpUBkoMkuAwBzGsYN+ELxKiB9lQ04/aPL3iKEnd5XuY9Ar2+W0NP3CKK7TiDzHDDV34ffTV/rGwFK2hMgrOE5jUrebjP/cfgsmA=
  on:
    branch: master
    tags: false
