language: python
python: 2.7

install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls

script: coverage run --source=cloudshell_rest_api setup.py test

after_success: coveralls


