language: python
python: 2.7
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls
script: coverage run --source=cloudshell_rest_api setup.py test
after_success: coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist
  user: Quali
  password:
    secure: KGkDZWdiQvZfsU2IHhzy/aXumYKnXyr0et16pIdKrr7toVElaJcVO3bjl0gq6UuQfGzxeKrkIU7nqiovBQ4d8APO4F+9q+mYSexVCVnW1eBf8/L0O4Zq+olhIY0uNOPib+jYIFD/Wx0NdcxRQVwDgLn43z0rsJ2fNTuS3Q39bdXrD+ToowXNzFz3t9N412e8J/R5sUkVagrRDehZcRNrNcajRGl4GcYrpEng3BapMBJDy1rrt+wjKVW4NrkySk+NRnDLbPYt0xAkCT/AlTMA+imCzTQGqjAEzfWC/Sa1qvHK86pUgtrYuqoPJUE4OiERBdf+VRrtLIg28Lt8xpDJ8fBScDO6tngFE5A5aszQv8mR17JHpUrzMwkjXgSqdxbKbQOOfsUaI3M8cQfwkirkjJC+EEEWUPZqo4oeYJwb5I3zFZc9GOJUtxQ8N+zk0HEnA4WgM53Vz1RKHYYDOE2gnp59iC+Pim5xyJf8c1PUMZFr2IgzGOdRbiase2yNVxdx7rZ0/z7H+DKCs506dkfADsTxURvuAOV24h+/mmD8TPUjZm0oSo7MnMWOEGCgNPcQGAm87ZLSaH/IEwHMteGx32RcURk6sYbdlk29bl61GwvCmMWMgDMKQCItkvqQKQe+oUCg2FWStsppiWCvzlyAaNoUC1/LOKH4ROWDCmyWv+g=
  on:
    branch: master
    tags: false