language: python
python: 2.7
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls
script: coverage run --source=cloudshell_rest_api setup.py test
after_success: coveralls
deploy:
    skip_cleanup: true
    provider: pypi
    distributions: sdist
    user: Quali
    password:
      secure: KdA7g0OP68S63pZtF8YOZSW4LtqxOv4vmk0+AAXkZ/BJbW//fl6CuAbMgjk5cio6R+HrGrffFltSxWkOj2fSQnUOUpKAHFpmbdRCbhfpaG45AGW8v2eZ52EXZH01R6LQS+CvxHNUmUOiu1P85eO/KBS7FZkwbNmwo0Xaoo/n/EDZlhRPwYC2EilT29cNsEKB+joUeFFXiOmmOwGQYzo/qEab0CPnNsYhHP/PPWUx4Dj3DudfgMtGGJJVKfUshzkhuhJ7ENLlqaSN9Suz+eKYrI2JJ6eAptgH+pE22bSgLAM8RW8s11o7QWBs7yS0U1LhFegJWo0g9RUdB/4noFwocXkI23E9ekzrXS1v8ngja6+maXAJz8F18kIF0YODpYfX2NZ8Bb+2EFJ2nOi2BmqPW1c5j3gbtzaAO0NJ0vCcIX0w1PuS1RFxOx61YPq/U14PwmcUocb2XKh0Gx7aJd2t5Z4Px+ZGv0+tiEFliVt/GCg3PtDUJHPLMGFyGESTil2nGR3lhxFiAkMFCqnJSL0xTulWQ2qJfUPzJBZFY77xvIVwX5DOMfUYUMQoltgCAqGun6EPN5OB7h/3U4nrQ2FcER8Tbr/hPWR1BqDRf3pw/nGZm74OgdK6gO/jEgU+oZbFfTNwL55t/UkopAvzL/XjWHTCMjpwUFV9lCihU4ks9+c=
    on:
      branch: master
      tags: false